// Code generated by "stringer -type=register"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fieldIoConnection-0]
	_ = x[registerCount-1]
}

const _register_name = "fieldIoConnectionregisterCount"

var _register_index = [...]uint8{0, 17, 30}

func (i register) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_register_index)-1 {
		return "register(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _register_name[_register_index[idx]:_register_index[idx+1]]
}
